# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Diggins @ Astroknit
email: john@jdiggins.com
description: > # this means to ignore newlines until "baseurl:"
  Thanks for checking out my site!  More coming soon!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jdiggins.com" # the base hostname & protocol for your site
twitter_username: astroknit
github_username:  astroknit

# Build settings
markdown: kramdown
